[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "5.0.8"
serde = { version = "1.0", features = ["derive"] }
alloy-sol-types = { workspace = true }
defi-lib = { path = "../lib" }
